### ISSUE TITLE
Allow 4-character hex colors

### ISSUE THREAD

**Issue by crb233** [Auroriax/PuzzleScriptPlus#65]
Currently, 3 (#RGB) 6 (#RRGGBB), and 8 (#RRGGBBAA) character hex colors are allowed. Why not also 4 (#RGBA)?

The major use-case for me is that I like choosing colors from the smaller 3-character palette with only 4096 colors. In order to add an alpha channel, I have to rewrite these as 6-character colors and then add the alpha. I took a quick look through the code and it seems like this should be an easy change.

**Comment by david-pfx** [comment]
This looks easy enough: a regex in colors.js and a conversion function in codemirror.js. Or am I missing something?

Is there an existing test program for colours anywhere?

**Comment by Auroriax** [comment]
I think you'd need to adjust the `isColor()` function in `compiler.js`, that might be enough already? I believe four character hex colors are accepted as-is in JS so you shouldn't need to do any super special parsing.

You can look at the commits that added semi-transparent colors to get an idea of what kind of change should be needed: `743a816 - Parse transparent colors correctly`.
And then you'll likely need to adjust `codemirror.js` as well so that the editor text won't render transparently (I originally fixed it in `3a05887 - Transparent colors are no longer displayed in transparent text`, but it was a hacky fix that will likely break with #RGBA.)

**Comment by david-pfx** [comment]
I'm sure I can fix the code (thanks for the pointers) but I really really need to write a test for it first. Where are the tests (if any) or where should I put one?

**Comment by david-pfx** [comment]
There were 2 regexes to fix. They are duplicates, the other is in color.js. Ideally they should be refactored.
I've written a test program.
Now what?

**Comment by Auroriax** [comment]
You can make a pull request with the fixes! Then I'll review it when I have time.

**Comment by david-pfx** [comment]
The fixes are just a few changed characters in two regexes, which on its own is hardly worth a PR.

But I've also written a test program, which I'd like to add but don't know how.

PS is using a unit test framework but I agree, testing a language is different (that's my day job). I have some ideas, but for later. For now, I'll just add a program to the suite if I know how.

**Comment by Auroriax** [comment]
Consider making a PR anyway, no changes are too small for a PR. (Generally the easier you'll make it for me to review the code the faster I can get to it.) Please see the readme for etiquette regarding PRs. What other way did you have in mind for pushing the changes? 🤔 

Consider submitting a separate PR for the test program and then I'll take a look to see where it makes sense.

(This is getting very off-topic for this specific issue though, please open a PRs as described above, or open a new issue if you'd like to discuss this subject further. Thank you!)

**Comment by david-pfx** [comment]
My intention was either (a) just send you a patch (which is the way the Linux guys always used to do it in the early days of Git) or (b) submit a PR that includes the test program. That’s always been my custom: fixes and test programs belong together.

 

But please note I don’t think I can submit a PR on PS+ through GitHub because I can’t fork it, which is because I already have a PS fork. So right now I’m not sure how to do a PR either.

 

Regards

David M Bennett FACS

  _____  

Polyomino Games – Programming Languages and Players for Games and Puzzles -- http://www.polyomino.com <http://www.polyomino.com/>

**Comment by Auroriax** [comment]
The PR was merged in, now this is valid (using the example from David's test project):
```
I
#Fff8 #F008 #0F08 #00F8 #0008
01234
12340
23401
34012
40123
```
