### ISSUE TITLE
Make Runtime Metadata Twiddling affect Color Palette.

### ISSUE THREAD

**Issue by Stingby12** [Auroriax/PuzzleScriptPlus#84]
![image](https://user-images.githubusercontent.com/85991163/218729387-f4a070cd-dde0-4bfb-b06c-bdae350bdde5.png)

**Comment by Auroriax** [comment]
Sorry, but I don't really see why this would be easier than simply swapping sprites, which also gives you more control over the colors you can use. Can you explain why you'd want this?

**Comment by Stingby12** [comment]
Because you have almost every Metadata info you can edit in game except
Color Palette.

**Comment by Auroriax** [comment]
Color pallettes feels like one of those features that's useful for a quick start but not really for more advanced development, I think. And because of a technical limitation (color names are replaced with hex codes during compilation in `generateExtraMembers`, rather than at runtime) this is not possible to support. I'd rather include this as part of a more flexible system like #34 .

**Comment by Stingby12** [comment]
Why not using Metadata Twiddling affect custom color paletes ?
